### ISSUE TITLE
请问数据库表结构怎么获取

### ISSUE THREAD

**Issue by JiancongLee** [haijiangxu/qff#1]
如题

**Comment by haijiangxu** [comment]
数据库使用mongodb，表结构直接与存入的数据DataFrame结构一致。
查询方法：
1、安装mongodb，推荐直接拉取docker镜像
2、安装qff
3、运行qff config 配置dburl
4、运行qff save保存股票历史数据
5、运行qff dbinfo 可查看数据库结构信息。
![dbinfo](https://user-images.githubusercontent.com/2928281/211995308-9239cb74-c18a-4b22-9a16-a8aa6de4b0f5.PNG)

**Comment by JiancongLee** [comment]
> 数据库使用mongodb，表结构直接与存入的数据DataFrame结构一致。 查询方法： 1、安装mongodb，推荐直接拉取docker镜像 2、安装qff 3、运行qff config 配置dburl 4、运行qff save保存股票历史数据 5、运行qff dbinfo 可查看数据库结构信息。 ![dbinfo](https://user-images.githubusercontent.com/2928281/211995308-9239cb74-c18a-4b22-9a16-a8aa6de4b0f5.PNG)

谢谢
